USE RESTO
GO

-- QUERY DE LOS USUARIOS
	SELECT 
		ID_USUARIO, 
		NOMBRE_USUARIO, 
		CONTRASENA, 
		TIPO,
		URL_IMAGEN, 
		ESTADO
	FROM USUARIOS U 
	LEFT JOIN IMAGENES I ON I.ID_IMAGEN = U.ID_IMAGEN

-- QUERY DE LOS MESEROS
	SELECT 
		ID_MESERO,
		ID_USUARIO, 
		DNI, 
		NOMBRE, 
		APELLIDO,
		TELEFONO, 
		DIRECCION,
		FECHA_NACIMIENTO,
		MAIL,
		ESTADO
	FROM MESEROS U 

-- QUERY DE LOS ADM
	SELECT 
		ID_ADMINISTRADOR,
		ID_USUARIO, 
		DNI, 
		NOMBRE, 
		APELLIDO,
		TELEFONO, 
		DIRECCION,
		FECHA_NACIMIENTO,
		MAIL,
		ESTADO
	FROM ADMINISTRADOR U 

-- INSERT DE UNA IMAGEN
	INSERT INTO IMAGENES(URL_IMAGEN) VALUES (@URL)
	UPDATE USUARIOS SET ID_IMAGEN = (SELECT MAX(ID_IMAGEN) FROM IMAGENES) WHERE ID_USUARIO = @IDUSUARIO