-- ELIMINAR BASE DE DATOS
	USE master
	DROP DATABASE RESTO
	GO
	USE MASTER
	GO

-- CREACION DE LA BASE DE DATOS
	CREATE DATABASE RESTO
	GO
	USE RESTO
	GO

-- CREACION DE TABLAS
CREATE TABLE IMAGENES(
	ID_IMAGEN INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	URL_IMAGEN VARCHAR(200) NULL
)
GO
CREATE TABLE USUARIOS (
    ID_USUARIO INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    NOMBRE_USUARIO VARCHAR(50) UNIQUE NOT NULL,
    CONTRASENA VARCHAR(30) NOT NULL,
    TIPO VARCHAR(20) NOT NULL CHECK (TIPO IN ('Administrador', 'Mesero')),
	ID_IMAGEN INT NULL,
	FOREIGN KEY (ID_IMAGEN) REFERENCES IMAGENES(ID_IMAGEN),
	ESTADO BIT NOT NULL DEFAULT(1)
)
GO
CREATE TABLE MESEROS (
    ID_MESERO INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	ID_USUARIO INT NULL,
	DNI VARCHAR(10) NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    APELLIDO VARCHAR(100) NOT NULL,
    TELEFONO VARCHAR(15) NOT NULL,
    DIRECCION VARCHAR(100) NOT NULL,
    FECHA_NACIMIENTO DATE NOT NULL CHECK(FECHA_NACIMIENTO <= GETDATE()),
    MAIL VARCHAR(50) UNIQUE NOT NULL,
    ESTADO BIT DEFAULT(1) NOT NULL,
	FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
)
GO
CREATE TABLE ADMINISTRADOR (
    ID_ADMINISTRADOR INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	ID_USUARIO INT NOT NULL,
	DNI VARCHAR(10) NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    APELLIDO VARCHAR(100) NOT NULL,
    TELEFONO VARCHAR(15) NOT NULL,
    DIRECCION VARCHAR(100) NOT NULL,
    FECHA_NACIMIENTO DATE NOT NULL CHECK(FECHA_NACIMIENTO <= GETDATE()),
    MAIL VARCHAR(50) UNIQUE NOT NULL,
    ESTADO BIT DEFAULT(1) NOT NULL,
	FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
)
GO
CREATE TABLE JORNADAS(
    ID_JORNADA INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    TIPO_JORNADA varchar (60) not null
)
GO
CREATE TABLE HORARIOS (
    ID_HORARIO INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	ID_JORNADA INT NOT NULL FOREIGN KEY REFERENCES JORNADAS(ID_JORNADA),
	HORA TIME NOT NULL,
	DISPONIBILIDAD BIT NOT NULL default(1)
)

-- INSERTS CON INFORMACIÓN PARA CADA TABLA

INSERT INTO JORNADAS (TIPO_JORNADA)
VALUES('Mañana'), ('Tarde'), ('Noche')
---------------------

INSERT INTO HORARIOS (ID_JORNADA, HORA, DISPONIBILIDAD)
VALUES (1,'08:00', 1),
	(1,'09:00', 1),
	(1,'10:00', 1),
	(1,'11:00', 1),
	(2,'12:00', 1),
	(2,'13:00', 1),
	(2,'14:00', 1),
	(2,'15:00', 1),
	(2,'16:00', 1),
	(3,'17:00', 1),
	(3,'18:00', 1),
	(3,'19:00', 1),
	(3,'20:00', 1),
    (3,'21:00', 1),
    (3,'22:00', 1)

---------------------

INSERT INTO USUARIOS (NOMBRE_USUARIO, CONTRASENA, TIPO) 
VALUES ('Sofia', '123', 'Mesero'), -- Usuarios de los meseros
       ('Gabriel', '123', 'Mesero'),
       ('Laura', '123', 'Mesero'),
       ('Martin', '123', 'Mesero'),
	   ('Alejandro', '123', 'Mesero'),
	   ('Admin1', '123', 'Administrador') -- Administrador

---------------------

INSERT INTO ADMINISTRADOR (ID_USUARIO, DNI, NOMBRE, APELLIDO, TELEFONO, DIRECCION, FECHA_NACIMIENTO, MAIL, ESTADO)
VALUES  (6, '122222789', 'Carlos', 'González', '1541234567', 'Av. Principal 123', '1980-04-12', 'carlos.gonzalez@email.com', 1)

---------------------

INSERT INTO MESEROS (ID_USUARIO, DNI, NOMBRE, APELLIDO, TELEFONO, DIRECCION, FECHA_NACIMIENTO, MAIL, ESTADO)
VALUES (1, '11111111', 'Mesero1', 'Apellido1', '1234567891', 'Dirección1', '1990-01-01', 'mesero1@mail.com', 1),
       (2, '11222222','Mesero2', 'Apellido2', '1234567892', 'Dirección2', '1990-02-02', 'mesero2@mail.com', 1),
       (3, '11333333','Mesero3', 'Apellido3', '1234567893', 'Dirección3', '1990-03-03', 'mesero3@mail.com', 1),
       (4, '11444444','Mesero4', 'Apellido4', '1234567894', 'Dirección4', '1990-04-04', 'mesero4@mail.com', 1)